AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - '**/*_pb.rb'
    - 'app/controllers/devise_custom/**/*'
    - 'app/reports/*'
    - 'bin/*'
    - 'config/**/*'
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'spec/dummy/**/*'
    - 'tmp/**/*'
    - 'vendor/bundle/**/*'
Metrics/AbcSize:
  Enabled: true
  Max: 16
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'
Metrics/ClassLength:
  Enabled: true
Metrics/CyclomaticComplexity:
  Enabled: true
Metrics/LineLength:
  Enabled: true
  Max: 100
Metrics/MethodLength:
  Enabled: true
Rails/ActionFilter:
  Enabled: false
Rails/HttpPositionalArguments:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/PredicateName:
  Enabled: false
