module.exports = {
  "extends": ["eslint:recommended"],
  "rules": {
    "arrow-parens": ["warn", "as-needed"],
    "brace-style": ["error", "1tbs", {"allowSingleLine": true}],
    "camelcase": "warn",
    "comma-spacing": "warn",
    "curly": ["error", "multi-line"],
    "dot-notation": "warn",
    "eol-last": "warn",
    "eqeqeq": ["warn", "allow-null"],
    "indent": ["error", "tab", {"SwitchCase": 1}],
    "jsx-quotes": ["error", "prefer-double"],
    "key-spacing": "warn",
    "keyword-spacing": "error",
    "max-len": ["warn", 140],
    "no-case-declarations": "off",
    "no-class-assign": "off",
    "no-console": "warn",
    "no-mixed-spaces-and-tabs": ["error", "smart-tabs"],
    "no-multi-spaces": "warn",
    "no-nested-ternary": "error",
    "no-unused-vars": ["warn", {"vars": "local", "args": "none"}],
    "no-whitespace-before-property": "warn",
    "prefer-template": "warn",
    "quote-props": ["warn", "as-needed"],
    "quotes": ["error", "single", "avoid-escape"],
    "semi": ["warn", "always", {"omitLastInOneLineBlock": true}],
    "space-before-blocks": ["error", "always"],
    "space-before-function-paren": ["error", "never"],
    "space-infix-ops": "warn",
    "strict": ["warn", "never"]
  }
}
